version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/nginx.conf.tmp
      - $DEMOAPPLOC:/demo-app
    ports:
      - ${PORT}:${PORT}
    networks:
      - workflow-network
    depends_on:
      - "backend"
    environment:
      - CODALAB=${CODALAB}
      - PORT=${PORT}
    command: /bin/bash -c "envsubst '\\\$$PORT \\\$$CODALAB' < /nginx.conf.tmp > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"

  backend:
    image: jyh1/workflow:server-demo
    container_name: codalab-worflow-server
    volumes:
      - ${SERVERBIN}:/server-bin
      - ${FRONTEND}:/static
    command: /server-bin
    expose:
      - "80"
    networks:
      - workflow-network
    depends_on:
      - "db"
    environment:
      - PORT=80
      - ENV=${ENV}
      - CODALAB=${CODALAB}
      - MYSQL_USER=workflow
      - MYSQL_DATABASE=codalab_workflow
      - MYSQL_PWD=workflowpw
      - MIGRATION=${MIGRATION}
      - MYSQL_HOST=db
      - DEMO=${DEMO}
      - PUBLICUSER=${PUBLICUSER}

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "${MYSQLDATA}:/var/lib/mysql"
    networks:
      - workflow-network
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_DATABASE=codalab_workflow
      - MYSQL_USER=workflow
      - MYSQL_PASSWORD=workflowpw

networks:
  workflow-network:
